version: '3'

services:
  redis:
    image: redis:alpine
    restart: always

  app:
    build: ./nc
    restart: always
    volumes:
      - NextCloud_Data:/var/www/html:z
    environment:
      - REDIS_HOST=redis
      - OC_trusted_domains=*
    depends_on:
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 0.0.0.0:8085:80
    volumes:
      - NextCloud_Data:/var/www/html:z,ro
    depends_on:
      - app

  cron:
    build: ./nc
    restart: always
    volumes:
      - NextCloud_Data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - redis

volumes:
  NextCloud_Data:
    external: true
